feat: Add endpoint for parsed clinvar copy number gain/loss
cancervariants/variation-normalization pull request #286
Opened 2022-05-02 15:10 UTC by korikuzma

Closes #285 

Notes:
- Didn't know what to put for the text variation definition. I just used params as the label. @larrybabb is this ok?

2022-05-02 16:39 UTC, larrybabb commented
@korikuzma 
```
 ParsedToAbsCnvService:
    """Given parsed ClinVar Copy Number Gain/Loss components, return Absolute
    Copy Number Variation
    :param int start: Start position as residue coordinate
    :param int end: End position as residue coordinate
    :param int total_copies: Total copies for Absolute Copy Number variation object
    :param Optional[ClinVarAssembly] assembly: Assembly. If `accession` is set,
        will ignore `assembly` and `chr`. If `accession` not set, must provide
        both `assembly` and `chr`.
    :param Optional[str] chr: Chromosome. Must set when `assembly` is set.
    :param Optional[str] accession: Accession.If `accession` is set,
        will ignore `assembly` and `chr`. If `accession` not set, must provide
        both `assembly` and `chr`.
    :return: Tuple containing Absolute Copy Number variation and list of warnings
    """
```
Wouldn't it make more sense to use `start`, `end`, `copies`, `assembly`, `chromosome`, `accession` instead of `param` for each arg, respectively?

2022-05-02 16:50 UTC, korikuzma commented
> @korikuzma
> 
> ```
>  ParsedToAbsCnvService:
>     """Given parsed ClinVar Copy Number Gain/Loss components, return Absolute
>     Copy Number Variation
>     :param int start: Start position as residue coordinate
>     :param int end: End position as residue coordinate
>     :param int total_copies: Total copies for Absolute Copy Number variation object
>     :param Optional[ClinVarAssembly] assembly: Assembly. If `accession` is set,
>         will ignore `assembly` and `chr`. If `accession` not set, must provide
>         both `assembly` and `chr`.
>     :param Optional[str] chr: Chromosome. Must set when `assembly` is set.
>     :param Optional[str] accession: Accession.If `accession` is set,
>         will ignore `assembly` and `chr`. If `accession` not set, must provide
>         both `assembly` and `chr`.
>     :return: Tuple containing Absolute Copy Number variation and list of warnings
>     """
> ```
> 
> Wouldn't it make more sense to use `start`, `end`, `copies`, `assembly`, `chromosome`, `accession` instead of `param` for each arg, respectively?

The `:param` is docstrings. [These](https://github.com/cancervariants/variation-normalization/blob/issue-285/variation/main.py#L528-L533) are the parameters I have for the endpoint.

2022-05-03 16:55 UTC, jsstevenson requested changes
typo

2022-05-03 16:55 UTC, jsstevenson commented on variation/main.py
> +    :param Optional[str] accession: Accession.If `accession` is set,
`Accession. If`

2022-05-03 17:03 UTC, jsstevenson approved these changes
typo free!

2022-05-03 17:09 UTC, merged